version: '3.9'
services:
  dagster-dagit:
    image: dagster-sklearn
    ports:
      - 3000:3000
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
  dagster-daemon:
    image: dagster-daemon
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
  dagster-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
volumes:
  dagster-postgres:
    driver: local
